### ISSUE TITLE
Error "INVALID_SIGNATURE" when using --data

### ISSUE THREAD

**Issue by noelno** [denouche/ovh-api-bash-client#6]
Hello,

I've noticed the following problem when using ovh-api-bash-client.sh with **Git Bash for Windows** : when I'm using the `--data` flag, the response is always :

```json
{"errorCode":"INVALID_SIGNATURE","httpCode":"400 Bad Request","message":"Invalid signature"}
```

For exemple when I try this request : 

```sh
$ ./ovh-api-bash-client.sh --url "/domain/zone/mywebsite.com/record/"
```

The response does returns the records. But when I specify a parameter :

```sh
$ ./ovh-api-bash-client.sh --url "/domain/zone/mywebsite.com/record/" --data "{'fieldType': 'TXT'}"
```

The response is :

```json
{"errorCode":"INVALID_SIGNATURE","httpCode":"400 Bad Request","message":"Invalid signature"}
```

**Comment by denouche** [comment]
Hi

I'm not using this Operating System so I cannot help you debugging.

But you could first check that `sha1sum` and `date '+%s'` commands are available on git bash and have the same behavior than Linux ones. This commands are used to calculate the requests signatures.

If you find the problem and can fix it without breaking the Linux support, do not hesitate to make a pull request, this could help some others Windows users.

Thanks

**Comment by bonidier** [comment]
@denouche I suggest adding a check of external dependencies with the  `which` command 
This will notify about what's missing

**Comment by noelno** [comment]
As for me, `sha1sum` and `date` are available (I checked with `which`), and `date '+%s'` returns the same timestamp as the one given by `curl https://eu.api.ovh.com/1.0/auth/time`.

I keep looking for a solution, but it may take a little time since I'm a script shell newbie.

**Comment by denouche** [comment]
What is the purpose of your request?
`$ ./ovh-api-bash-client.sh --url "/domain/zone/mywebsite.com/record/" --data "{'fieldType': 'TXT'}"`

The `--data` flag is used to add a body to the HTTP request, so it's should be a `PUT` or `POST` request. 
You **have to** explicitly tell what is the HTTP verb to use, by using the `--method` flag.

In your command you didn't specified it, so by default it's a `GET`, that's why the error occurs. A `GET` request cannot have a body.

**Comment by denouche** [comment]
If you want to use this request: `https://api.ovh.com/console/#/domain/zone/%7BzoneName%7D/record#GET`, you cannot give the parameters using the `--data` flag. This is a `GET` request so it does not have a body. In this case this is a query parameter.

There is differents types of request parameters, and there are all differents.
- URL parameters, for exemple `{zoneName}` in your example.
- Query parameters, for exemple `fieldType` in the API you try to request. These parameters are located after the  `?` in the URL
- body parameters
- headers

To know which one you have to use in your requests, give a try to the OVH API Console, and take a look to the  `Raw` tab after executing the request.
![query](https://user-images.githubusercontent.com/3081451/30579406-df60026a-9d18-11e7-8da6-ed13bd703616.png)

Here you can see that the `fieldType` parameter is in the URL, after the `?` sign. So it's a query parameter.

So to call this API using ovh-api-bash-client you should try:
`./ovh-api-bash-client.sh --url "/domain/zone/mywebsite.com/record/?fieldType=TXT"`

**Comment by noelno** [comment]
You're right, I was putting the query parameter in the body. 

Now with `./ovh-api-bash-client.sh --url "/domain/zone/mywebsite.com/record/?fieldType=TXT"` it works. Thanks !
