### ISSUE TITLE
libs JSON.sh

### ISSUE THREAD

**Issue by JBerghof** [denouche/ovh-api-bash-client#8]
Hi, since a few reviews their is some troubles with the libs "JSON.sh". One of my server use the commit id "5719c46b2dc10183c058146f0c5ff0e2405dd912" and i didn't remember any trouble with this part.

The script is seeking for ovh-api-bash-client/libs/JSON.sh but now this "lib" is in the "contrib" directory.
The script is also seeking for ovh-api-bash-client/JSON.sh which is still in the "contrib" directory.

I don't know if i should open an other issue, but well, the "consumerKey" URL than the script should give is "empty". See screen below.

![image](https://user-images.githubusercontent.com/26378563/36420272-c58b4bf2-1634-11e8-9778-6b2becd0f6a6.png)

Edit: Well i forget, thanks for this client, i really appreciate it ! :)
Edit2: I will try to fix all this and push a PR since i'm comfortable with bash if i can find some times :).

**Comment by denouche** [comment]
Hi
Did you executed `make install` instruction before to run the `./ovh-api-bash-client.sh --initApp` command?

**Comment by JBerghof** [comment]
Mpfh nope, my bad i missed this on the "installation instruction" part.
Sorry for inconvenience.
